export const ADD_DONUT_TO_ORDER = 'ADD_DONUT_TO_ORDER';
export const REMOVE_DONUT_FROM_ORDER = 'REMOVE_DONUT_FROM_ORDER';
export const UPDATE_ORDER_QUANTITY = 'UPDATE_ORDER_QUANTITY';
export const ADD_MULTIPLE_TO_ORDER = 'ADD_MULTIPLE_TO_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const TOGGLE_ORDER = 'TOGGLE_ORDER';

ADD_DONUT_TO_ORDER,
// ADD_TO_CART || Add donut to order
REMOVE_DONUT_FROM_ORDER,
// REMOVE_FROM_CART || Remove donut from order
UPDATE_ORDER_QUANTITY,
// UPDATE_CART_QUANTITY || Update order quantity
ADD_MULTIPLE_TO_ORDER,
// ADD_MULTIPLE_TO_CART,
CLEAR_ORDER,
// CLEAR_CART,
TOGGLE_ORDER
// TOGGLE_CART,
