export const UPDATE_DONUTS = 'UPDATE_DONUTS';
export const ADD_DONUT_TO_ORDER = 'ADD_DONUT_TO_ORDER';
export const REMOVE_DONUT_FROM_ORDER = 'REMOVE_DONUT_FROM_ORDER';
export const UPDATE_ORDER_QUANTITY = 'UPDATE_ORDER_QUANTITY';
export const ADD_MULTIPLE_TO_ORDER = 'ADD_MULTIPLE_TO_ORDER';
export const ADD_ORDER_TO_USERORDER = 'ADD_ORDER_TO_USERORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const TOGGLE_ORDER = 'TOGGLE_ORDER';
